### ISSUE TITLE
Page not loading correctly on some URLs

### ISSUE THREAD

**Issue by wilos** [MegatronKing/NetBare#11]
We are seeing on some pages that they are not being loaded correctly and the screen remains blank in Chrome, e.g. 

https://meteoexploration.com/

In logcat, we see several entries like this:

2019-02-15 13:07:48.896 1331-1569/com.github.megatronking.netbare.sample E/NetBare: java.io.EOFException: Read error

Error is reproducible. Tested with latest Netbare sample on Android 8.1 device

**Comment by MegatronKing** [comment]
Fixed!

**Comment by wilos** [comment]
I can confirm that this is fixed, thank you!
