### ISSUE TITLE
Occasional SSL error

### ISSUE THREAD

**Issue by wilos** [MegatronKing/NetBare#17]
Device: Android 8.1
Latest version of NetBare Sample

I am occasionally seeing the following error being reported in logcat when navigating with Chrome to different pages:

2019-02-25 11:47:58.857 12434-13122/com.github.megatronking.netbare.sample E/NetBare: Read error: ssl=0xa807b180: Failure in SSL library, usually a protocol error
    error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:579 0x97773ae0:0x00000001)

Was not able to reproduce this error by re-loading the page, so it may be a random error that is difficult to reproduce.

The page still loaded fine in Chrome, there were no visible signs of a problem.

**Comment by MegatronKing** [comment]
It was caused by self signed certificate, NetBare cannot do anything.
