### ISSUE TITLE
HttpSSLCodecInterceptor 无法处理过长的响应消息

### ISSUE THREAD

**Issue by ilovechocolate** [MegatronKing/NetBare#22]
测试某些响应内容过长的接口，如 https://api.apiopen.top/todayVideo 时，intercept 拦截到的数据会被截断

**Comment by MegatronKing** [comment]
除了Header区域是整段回调的，Body区域都是分段回调的。这么做的原因是，比如10G大小的Body不可能直接一次性给你，首先内存就吃不住10G。所以目前都是流式分段处理，具体每个段是不固定的，按照每个IP包中包含的数据量而定。

**Comment by ilovechocolate** [comment]
感谢及时回复。
我理解你所说的对body数据进行分段处理，但是我这边测试到的情况是，分段后的数据存在丢失的情况，也即，无法获取当前会话的所有响应数据，由于onResponseFinished很多情况下没有成功回调，不知是否有方法能检查body域的完整性，或者获得总分段数？

**Comment by lueans** [comment]
hi 请问下有没有获取body完整的解决方案

**Comment by MegatronKing** [comment]
可以参考：https://stackoverflow.com/questions/4824451/detect-end-of-http-request-body。
总结下就是，无论是请求体还是响应体都是分两种情况：第一种是直接包含content-length的，content-length的值是多少，body长度就是多少（字节）；第二种是不包含content-length（即chunked格式），这个稍微麻烦一点，需要边读边解析chunk，直到解析到zero chunk为止，请参考https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding , 同时还必须注意body后面还可能有trailers：https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer。

**Comment by houyidg** [comment]
已经成功解析了chunk zip数据，以及原始数据chunk、zip化，篡改数据

**Comment by xsk666** [comment]
> 已经成功解析了chunk zip数据，以及原始数据chunk、zip化，篡改数据

能不能开源呢，想学习一下
