### ISSUE TITLE
代理访问

### ISSUE THREAD

**Issue by jsonabs** [MegatronKing/NetBare#23]
作者您好
[将百度首页的logo图片修改成自定义的图片]功能, 我希望用代理ip和代理端口去把数据发送给服务端,或者在request的时候把地址替换成本地地址(访问本地资源不去访问服务器),例如:把https://m.baidu.com/static/index/plus/plus_logo.png替换成http://192.168.1.1/static/index/plus/plus_logo.png
我应该怎么做?有空的话麻烦看下,谢谢了

**Comment by jsonabs** [comment]
按照介绍尝试在onRequestInject修改了url,测试结果请求的path改了,但是请求的host不能修改

**Comment by Stxr** [comment]
楼主问题解决了吗？
