### ISSUE TITLE
如何获取那个tcp请求是哪个app触发的

### ISSUE THREAD

**Issue by hhhaiai** [MegatronKing/NetBare#33]
如何获取那个tcp请求是哪个app触发的

**Comment by MegatronKing** [comment]
https://github.com/MegatronKing/NetBare/blob/master/netbare-core/src/main/java/com/github/megatronking/netbare/net/UidDumper.java

**Comment by hhhaiai** [comment]
get it 。 3Q

**Comment by scorpiokara** [comment]
请问，这个UidDumper.java ，是如何使用的，怎么知道哪个app触发的？？
