### ISSUE TITLE
Not in GZIP format

### ISSUE THREAD

**Issue by Ezreal147** [MegatronKing/NetBare#35]
When my response body is too large,I met this promblem:
`java.util.zip.ZipException: Not in GZIP format`
and this is my code:
`var res=GZIPInputStream(HttpBodyInputStream(body)).bufferedReader(UTF_8).readText()`
how to solve this problem

**Comment by dexpota** [comment]
I have the same issue, how did you solve it? I guess it is because not all packets are available to correctly decompress the response.

**Comment by Ezreal147** [comment]
I saved the response buffers and merge them.

**Comment by dexpota** [comment]
Thank you, I am going to try it out.
