### ISSUE TITLE
能否实现拦截请求，并自己构造一个返回包，触发onResponseInject

### ISSUE THREAD

**Issue by Ezreal147** [MegatronKing/NetBare#42]

**Comment by Ezreal147** [comment]
能否在服务器未响应时，自己构造一个包返回，怎么触发onResponseInject

**Comment by cuisoap** [comment]
你可以等服务器响应的时候直接改变bytebuffer的内容完成response替换，服务器没有返回内容时onResponseInject不可能被单独触发。如果你想提前响应其实在tun(vpn establish返回的文件描述符)读到报文时直接构造响应的包返回是最快的

**Comment by Ezreal147** [comment]
我已经实现了，在TcpVATunnel里获取mgateway，然后调用mgateway.response(body)就可以了，即使拦截了request，服务器没有响应也是可以触发onResponseInject的

**Comment by Ezreal147** [comment]
我已经实现了，在TcpVATunnel里获取mgateway，然后调用mgateway.onResponse(body)就可以了，即使拦截了request，服务器没有响应也是可以触发onResponseInject的

**Comment by houyidg** [comment]
@Ezreal147 能共享一下代码吗？
