### ISSUE TITLE
Crash on Android 8.0 (SDK 26) devices

### ISSUE THREAD

**Issue by wilos** [MegatronKing/NetBare#5]
I did some tests on an Android 8.0 (SDK 26) device and also with the Android Studio 8.0 emulator. On both devices, as soon as the VPN tries to connect, the device crashes (and actually goes into an unstable state which needs a reboot to return to normal). Issue is 100% reproducible, I was never able to start the VPN without this crash occurring. Please let me know if you need more information

**Comment by MegatronKing** [comment]
It is an emulator bug, I fixed it.

**Comment by wilos** [comment]
Thanks, I can also confirm that this is now fixed on our 8.0 device too, great!
