### ISSUE TITLE
开启vpn之后，自己的应用第一次调接口会超时，或者https的会ssl握手失败

### ISSUE THREAD

**Issue by scorpiokara** [MegatronKing/NetBare#56]
HTTP FAILED: java.net.SocketTimeoutException: timeout
HTTP FAILED: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

之后在请求就又好了

然后我把超时时间改成60s，接口会等待60s之后成功返回

**Comment by halleyjin** [comment]
我们也是一模一样的情况

**Comment by scorpiokara** [comment]
> 我们也是一模一样的情况

后来有解决么，用的什么方法呀

**Comment by MegatronKing** [comment]
自签名证书，被测试的App需要移除证书绑定，然后把自签证书绑定到Netbare里面（需要加代码）。自签证书是个麻烦的事情，建议用CA签的证书测试。
