### ISSUE TITLE
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown

### ISSUE THREAD

**Issue by xiaobaiyey** [MegatronKing/NetBare#79]
部分应用抓包存在问题
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown

**Comment by xiaobaiyey** [comment]
找到问题了，证书问题，换个证书ok了，详细原因未知

**Comment by chenyang1900** [comment]
@xiaobaiyey  换新证书是怎么生成的
